/*
 * RoomManagerInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.DMView;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.omg.PortableServer.IdAssignmentPolicy;

import com.DMModel.Room;
import com.DMUtil.DMUtil;
import com.Dao.RoomDao;

/**
 *
 * @author  __USER__
 */
public class RoomManagerInterFrm extends javax.swing.JInternalFrame {
	DMUtil dmutil = new DMUtil();
	RoomDao roomdao = new RoomDao();

	/** Creates new form RoomManagerInterFrm */
	public RoomManagerInterFrm() {
		initComponents();
		this.setLocation(200, 50);
		this.fillTable(new Room());
	}

	private void fillTable(Room room) {
		DefaultTableModel dtm = (DefaultTableModel) table.getModel();
		dtm.setRowCount(0);
		Connection con = null;
		try {
			con = dmutil.getCon();
			ResultSet rs = roomdao.roomList(con, room);
			while (rs.next()) {
				Vector v = new Vector();
				v.add(rs.getString("id"));
				v.add(rs.getString("member"));
				v.add(rs.getString("leader"));
				dtm.addRow(v);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				dmutil.closeCon(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		roomNum = new javax.swing.JTextField();
		jb_search = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		idTxt = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		roomnumber = new javax.swing.JTextField();
		jb_modify = new javax.swing.JButton();
		jb_exit = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		roomleader = new javax.swing.JTextField();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u5bbf\u820d\u7ba1\u7406");

		jLabel1.setText("\u5bdd\u5ba4\u53f7\uff1a");

		jb_search.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\search.png")); // NOI18N
		jb_search.setText("\u67e5\u8be2");
		jb_search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_searchActionPerformed(evt);
			}
		});

		table.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "±àºÅ", "ÇÞÊÒºÅ", "ÇÞÊÒ³¤" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		table.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				tableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(table);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u8868\u5355\u64cd\u4f5c"));

		jLabel2.setText("\u7f16\u53f7\uff1a");

		idTxt.setEditable(false);

		jLabel3.setText("\u5bdd\u5ba4\u53f7\uff1a");

		jb_modify.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\modify.png")); // NOI18N
		jb_modify.setText("\u4fee\u6539");
		jb_modify.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_modifyActionPerformed(evt);
			}
		});

		jb_exit.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\exit.png")); // NOI18N
		jb_exit.setText("\u9000\u51fa");
		jb_exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_exitActionPerformed(evt);
			}
		});

		jLabel4.setText("\u5bdd\u5ba4\u957f\uff1a");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(39, 39, 39)
										.addComponent(jb_modify)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												162, Short.MAX_VALUE)
										.addComponent(jb_exit)
										.addGap(64, 64, 64))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(21, 21, 21)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel4)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																roomleader)
														.addComponent(
																idTxt,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																92,
																Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addComponent(jLabel3)
										.addGap(10, 10, 10)
										.addComponent(
												roomnumber,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												116, Short.MAX_VALUE)
										.addGap(62, 62, 62)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																idTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																roomnumber,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(33, 33, 33)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																roomleader,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												60, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jb_modify)
														.addComponent(jb_exit))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addComponent(roomNum,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										173, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jb_search).addGap(80, 80, 80))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.Alignment.LEADING,
														0,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														379, Short.MAX_VALUE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jb_search)
												.addComponent(
														roomNum,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										111,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jb_searchActionPerformed(java.awt.event.ActionEvent evt) {
		String member = roomNum.getText();
		Room room = new Room(member);
		this.fillTable(room);
	}

	private void jb_modifyActionPerformed(java.awt.event.ActionEvent evt) {
		String roomNumber = roomnumber.getText();
		String roomLeader = roomleader.getText();
		String id = idTxt.getText();
		Connection con = null;
		try {
			con = dmutil.getCon();
			Room room = new Room(id, roomNumber, roomLeader);
			int a = roomdao.roomModify(con, room);
			if (a == 1) {
				JOptionPane.showMessageDialog(null, "ÐÞ¸Ä³É¹¦£¡");
				resetValue();
				this.fillTable(new Room());
				return;
			} else {
				JOptionPane.showMessageDialog(null, "ÐÞ¸ÄÊ§°Ü!");
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "ÐÞ¸ÄÊ§°Ü!");
			e.printStackTrace();
		}
	}

	public void resetValue() {
		roomnumber.setText("");
		roomleader.setText("");
		idTxt.setText("");
	}

	private void jb_exitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(null, "ÊÇ·ñÍË³öÏµÍ³");
		if (result == 0) {
			this.dispose();
		}
	}

	private void tableMousePressed(java.awt.event.MouseEvent evt) {
		int row = table.getSelectedRow();
		idTxt.setText(table.getValueAt(row, 0) + "");
		roomnumber.setText(table.getValueAt(row, 1) + "");
		roomleader.setText(table.getValueAt(row, 2) + "");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField idTxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jb_exit;
	private javax.swing.JButton jb_modify;
	private javax.swing.JButton jb_search;
	private javax.swing.JTextField roomNum;
	private javax.swing.JTextField roomleader;
	private javax.swing.JTextField roomnumber;
	private javax.swing.JTable table;
	// End of variables declaration//GEN-END:variables

}